/**
 * ===========================================





















































































































































































































































































































































































































































































module.exports = BookmarkController;};  }    }      return serverError(res, 'Failed to toggle bookmark');      logger.error(`API Bookmark toggle error: ${error.message}`);      console.error(`[BOOKMARK_API] toggleBookmark() - Error: ${error.message}`);    } catch (error) {            });        } : null          createdAt: result.bookmark.createdAt          id: result.bookmark._id,        bookmark: result.bookmark ? {        isBookmarked: result.added,        comicParam,      return ok(res, `Bookmark ${action} successfully`, {            logger.info(`API Bookmark ${action}: ${username} -> ${comicParam}`);      console.log(`[BOOKMARK_API] ✓ Bookmark ${action}: ${username} -> ${comicParam}`);      const action = result.added ? 'added' : 'removed';            });        genres: comic.genres || []        latestChapter: comic.latest_chapter,        thumbnail: comic.thumbnail,        title: comic.title,      const result = await Bookmark.toggle(userId, comicParam, {      // Toggle bookmark            }        return notFound(res, 'Comic not found');        console.log(`[BOOKMARK_API] Comic not found: ${comicParam}`);      if (!comic) {            const comic = await ComicModel.findByParam(comicParam);      // Validate comic exists for new bookmarks    try {        logger.info(`API Bookmark toggle: ${username} -> ${comicParam}`);    console.log(`[BOOKMARK_API] toggleBookmark() - User: ${username}, Comic: ${comicParam}`);        const username = req.user.username;    const userId = req.user._id;    const { comicParam } = req.params;  async toggleBookmarkAPI(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request   *    * POST /api/bookmarks/:comicParam/toggle   *    * Toggle bookmark (add or remove) (API)  /**    },    }      return serverError(res, 'Failed to check bookmark status');      logger.error(`API Bookmark status error: ${error.message}`);      console.error(`[BOOKMARK_API] checkStatus() - Error: ${error.message}`);    } catch (error) {            });        isBookmarked        comicParam,      return ok(res, 'Bookmark status retrieved', {            const isBookmarked = await Bookmark.isBookmarked(userId, comicParam);    try {        console.log(`[BOOKMARK_API] checkStatus() - Comic: ${comicParam}`);        const userId = req.user._id;    const { comicParam } = req.params;  async checkBookmarkStatusAPI(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request   *    * GET /api/bookmarks/:comicParam/status   *    * Check if a comic is bookmarked (API)  /**    },    }      return serverError(res, 'Failed to retrieve bookmarks');      logger.error(`API Bookmark list error: ${error.message}`);      console.error(`[BOOKMARK_API] listBookmarks() - Error: ${error.message}`);    } catch (error) {            });        }          hasPrev: page > 1          hasNext: page < totalPages,          totalItems: totalBookmarks,          limit,          total: totalPages,          current: page,        pagination: {        })),          createdAt: b.createdAt          notes: b.notes,          comic: b.cachedComic,          comicParam: b.comicParam,          id: b._id,        bookmarks: bookmarks.map(b => ({      return ok(res, 'Bookmarks retrieved successfully', {            console.log(`[BOOKMARK_API] Found ${bookmarks.length} bookmarks`);            const totalPages = Math.ceil(totalBookmarks / limit);            ]);        Bookmark.countByUser(userId)        Bookmark.findByUser(userId, { limit, skip }),      const [bookmarks, totalBookmarks] = await Promise.all([    try {        logger.info(`API Bookmark list: ${username}, page ${page}`);    console.log(`[BOOKMARK_API] listBookmarks() - User: ${username}, Page: ${page}`);        const skip = (page - 1) * limit;    const limit = Math.min(parseInt(req.query.limit) || 20, 50);    const page = parseInt(req.query.page) || 1;    const username = req.user.username;    const userId = req.user._id;  async listBookmarksAPI(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request   *    * - limit: Items per page (default: 20, max: 50)   * - page: Page number (default: 1)   * Query Parameters:   *    * GET /api/bookmarks   *    * List user's bookmarks (API)  /**    },    }      return serverError(res, 'Failed to remove bookmark');      logger.error(`API Bookmark remove error: ${error.message}`);      console.error(`[BOOKMARK_API] removeBookmark() - Error: ${error.message}`);    } catch (error) {            });        removed: true        comicParam,      return ok(res, 'Bookmark removed successfully', {            logger.info(`API Bookmark removed: ${username} -> ${comicParam}`);      console.log(`[BOOKMARK_API] ✓ Bookmark removed: ${username} -> ${comicParam}`);            }        return notFound(res, 'Bookmark not found');        console.log(`[BOOKMARK_API] Bookmark not found: ${comicParam}`);      if (result.deletedCount === 0) {            const result = await Bookmark.deleteOne({ userId, comicParam });    try {        logger.info(`API Bookmark remove: ${username} -> ${comicParam}`);    console.log(`[BOOKMARK_API] removeBookmark() - User: ${username}, Comic: ${comicParam}`);        const username = req.user.username;    const userId = req.user._id;    const { comicParam } = req.params;  async removeBookmarkAPI(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request   *    * DELETE /api/bookmarks/:comicParam   *    * Remove a comic from user's bookmarks (API)  /**    },    }      return serverError(res, 'Failed to add bookmark');      logger.error(`API Bookmark add error: ${error.message}`);      console.error(`[BOOKMARK_API] addBookmark() - Error: ${error.message}`);            }        return conflict(res, 'Comic already bookmarked');      if (error.code === 11000) {      // Handle duplicate key error    } catch (error) {            });        }          createdAt: bookmark.createdAt          comic: bookmark.cachedComic,          comicParam: bookmark.comicParam,          id: bookmark._id,        bookmark: {      return created(res, 'Bookmark added successfully', {            logger.info(`API Bookmark created: ${username} -> ${comic.title}`);      console.log(`[BOOKMARK_API] ✓ Bookmark created: ${username} -> ${comic.title}`);            });        }          genres: comic.genres || []          latestChapter: comic.latest_chapter,          thumbnail: comic.thumbnail,          title: comic.title,        cachedComic: {        comicParam,        userId,      const bookmark = await Bookmark.create({      // Create bookmark            }        return conflict(res, 'Comic already bookmarked');        console.log(`[BOOKMARK_API] Already bookmarked: ${comicParam}`);      if (isAlreadyBookmarked) {            const isAlreadyBookmarked = await Bookmark.isBookmarked(userId, comicParam);      // Check if already bookmarked            }        return notFound(res, 'Comic not found');        console.log(`[BOOKMARK_API] Comic not found: ${comicParam}`);      if (!comic) {            const comic = await ComicModel.findByParam(comicParam);      // Validate comic exists in MySQL    try {        logger.info(`API Bookmark add: ${username} -> ${comicParam}`);    console.log(`[BOOKMARK_API] addBookmark() - User: ${username}, Comic: ${comicParam}`);        const username = req.user.username;    const userId = req.user._id;    const { comicParam } = req.params;  async addBookmarkAPI(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request   *    * POST /api/bookmarks/:comicParam   *    * Add a comic to user's bookmarks (API)  /**    // ===========================================  // API HANDLERS (JSON Response)  // ===========================================    },    }      });        message: 'Gagal memuat daftar bookmark'        title: 'Server Error',      res.status(500).render('errors/500', {      logger.error(`Bookmark list error: ${error.message}`);      console.error(`[BOOKMARK_CTRL] listBookmarksPage() - Error: ${error.message}`);    } catch (error) {            });        }          hasPrev: page > 1          hasNext: page < totalPages,          totalItems: totalBookmarks,          total: totalPages,          current: page,        pagination: {        bookmarks,        user: req.user.getPublicProfile(),        currentPage: 'bookmarks',        title: 'Bookmark Saya - AF-Komik',      res.render('pages/bookmarks', {      // Render bookmarks page            console.log(`[BOOKMARK_CTRL] Found ${bookmarks.length} bookmarks (total: ${totalBookmarks})`);            const totalPages = Math.ceil(totalBookmarks / limit);      // Calculate pagination            ]);        Bookmark.countByUser(userId)        Bookmark.findByUser(userId, { limit, skip }),      const [bookmarks, totalBookmarks] = await Promise.all([      // Fetch bookmarks and count in parallel    try {        logger.info(`Bookmark list view: ${username}, page ${page}`);    console.log(`[BOOKMARK_CTRL] listBookmarksPage() - User: ${username}, Page: ${page}`);        const skip = (page - 1) * limit;    const limit = 20;    const page = parseInt(req.query.page) || 1;    const username = req.user.username;    const userId = req.user._id;  async listBookmarksPage(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request   *    * Shows paginated list of user's bookmarked comics.   *    * GET /my/bookmarks   *    * Display user's bookmark list (Web)  /**    },    }      return res.redirect('/my/bookmarks?error=' + encodeURIComponent('Gagal menghapus bookmark'));      logger.error(`Bookmark remove error: ${error.message}`);      console.error(`[BOOKMARK_CTRL] removeBookmarkWeb() - Error: ${error.message}`);    } catch (error) {            return res.redirect(`/comics/${comicParam}?success=${encodeURIComponent('Berhasil dihapus dari bookmark')}`);            }        return res.redirect('/my/bookmarks?success=' + encodeURIComponent('Bookmark berhasil dihapus'));      if (referrer.includes('/my/bookmarks')) {            const referrer = req.get('Referrer') || '';      // Check referrer to redirect appropriately            logger.info(`Bookmark removed: ${username} -> ${comicParam}`);      console.log(`[BOOKMARK_CTRL] ✓ Bookmark removed: ${username} -> ${comicParam}`);            }        return res.redirect(`/my/bookmarks?info=${encodeURIComponent('Bookmark tidak ditemukan')}`);        console.log(`[BOOKMARK_CTRL] Bookmark not found for removal: ${comicParam}`);      if (result.deletedCount === 0) {            const result = await Bookmark.deleteOne({ userId, comicParam });      // Attempt to remove bookmark    try {        logger.info(`Bookmark remove request: ${username} -> ${comicParam}`);    console.log(`[BOOKMARK_CTRL] removeBookmarkWeb() - User: ${username}, Comic: ${comicParam}`);        const username = req.user.username;    const userId = req.user._id;    const { comicParam } = req.params;  async removeBookmarkWeb(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request   *    * POST /bookmarks/:comicParam/remove (or DELETE with method-override)   *    * Remove a comic from user's bookmarks (Web)  /**    },    }      return res.redirect(`/comics/${comicParam}?error=${encodeURIComponent('Gagal menambahkan bookmark')}`);      logger.error(`Bookmark add error: ${error.message}`);      console.error(`[BOOKMARK_CTRL] addBookmarkWeb() - Error: ${error.message}`);            }        return res.redirect(`/comics/${comicParam}?info=${encodeURIComponent('Komik sudah ada di bookmark')}`);        console.log(`[BOOKMARK_CTRL] Duplicate bookmark attempt: ${comicParam}`);      if (error.code === 11000) {      // Handle duplicate key error (race condition)    } catch (error) {            return res.redirect(`/comics/${comicParam}?success=${encodeURIComponent('Berhasil ditambahkan ke bookmark')}`);      // Redirect back to comic detail with success message            logger.info(`Bookmark created: ${username} -> ${comic.title}`);      console.log(`[BOOKMARK_CTRL] ✓ Bookmark added: ${username} -> ${comic.title}`);            });        }          genres: comic.genres || []          latestChapter: comic.latest_chapter,          thumbnail: comic.thumbnail,          title: comic.title,        cachedComic: {        comicParam,        userId,      await Bookmark.create({      // Create bookmark with cached comic data            }        return res.redirect(`/comics/${comicParam}?info=${encodeURIComponent('Komik sudah ada di bookmark')}`);        console.log(`[BOOKMARK_CTRL] Already bookmarked: ${username} -> ${comicParam}`);      if (isAlreadyBookmarked) {            const isAlreadyBookmarked = await Bookmark.isBookmarked(userId, comicParam);      // Check if already bookmarked            }        return res.redirect(`/comics?error=${encodeURIComponent('Komik tidak ditemukan')}`);        logger.warn(`Bookmark failed - comic not found: ${comicParam}`);        console.log(`[BOOKMARK_CTRL] Comic not found: ${comicParam}`);      if (!comic) {            const comic = await ComicModel.findByParam(comicParam);      // Validate comic exists in MySQL    try {        logger.info(`Bookmark add request: ${username} -> ${comicParam}`);    console.log(`[BOOKMARK_CTRL] addBookmarkWeb() - User: ${username}, Comic: ${comicParam}`);        const username = req.user.username;    const userId = req.user._id;    const { comicParam } = req.params;  async addBookmarkWeb(req, res) {   */   * @param {Object} res - Express response   * @param {Object} req - Express request (user attached by middleware)   *    * Caches comic data for quick display.   * Validates comic exists in MySQL before creating bookmark.   *    * POST /bookmarks/:comicParam   *    * Add a comic to user's bookmarks (Web)  /**    // ===========================================  // WEB HANDLERS (Redirect-based)  // ===========================================  const BookmarkController = { */ * Bookmark controller with web and API handlers/**} = require('../utils/apiResponse');  serverError   conflict,   notFound,   ok,   created,   errorResponse,   successResponse, const { const ComicModel = require('../models/mysql/comic.model');const Bookmark = require('../models/mongo/Bookmark');const logger = require('../config/logger'); */ * 4. Return response (redirect or JSON) * 3. Perform bookmark operation in MongoDB * 2. Validate comic exists in MySQL * 1. Validate user authentication * Data Flow: *  * - Comic existence validated against MySQL * - Users can only access their own bookmarks * - All operations require authentication * Security: *  * - Check bookmark status * - List user bookmarks (with pagination) * - Remove bookmark * - Add bookmark (with MySQL comic validation) * Features: *  * Provides both web (EJS redirect) and API (JSON) handlers. * Controller for handling bookmark operations. *  * =========================================== * AF-Komik V2 - Bookmark Controller * AF-Komik V2 - MongoDB Models Index
 * ===========================================
 * 
 * Central export point for all MongoDB models.
 * 
 * MongoDB is used ONLY for:
 * - Users (authentication data)
 * - Sessions (login sessions - managed by connect-mongo)
 * - Bookmarks (user bookmarks)
 * - Reading History (user progress tracking)
 * 
 * DO NOT add comic-related models here.
 * Comic data belongs in MySQL.
 */

const User = require('./User');
const Bookmark = require('./Bookmark');
const ReadingHistory = require('./ReadingHistory');

module.exports = {
  User,
  Bookmark,
  ReadingHistory
};
